### PR TITLE
Add preloader

### PR DESCRIPTION
**Pull request by littleprodigy**
# Description

Please include a brief description of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by littleprodigy** [comment]
Here is the link https://littleprodigy.github.io/GirlsDoCode/

**Comment by littleprodigy** [comment]
Ok, will do it.

**Comment by littleprodigy** [comment]
All the requested changes have been made.

**Comment by Anupam-dagar** [comment]
@littleprodigy this is wrong implementation to do a loader. It's hardcoded, loader should stay as long as website is loading, here it will stay only for 2 seconds. I am reverting this for now, count the points after you submit a new PR for this.

**Pull request merged**
