### PR TITLE
Add contributors section

### LINKED ISSUE #21: add a contributor section
add a contributor section which lists all the contributors contributing to CodeFemme

### PR DESCRIPTION
**Pull request by CleverFool77**
# Description

Contributors section added

Fixes #21 

screenshot from 2019-01-22 13-38-05

screenshot from 2019-01-22 13-39-47

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Jigar3** [comment]
@CleverFool77 Could you please share a live link for the same.

**Comment by Anupam-dagar** [comment]
@CleverFool77 tried the changes locally. 
screenshot from 2019-01-22 15-24-53

This needs a responsiveness fix for mobile screens.

**Comment by CleverFool77** [comment]
@Jigar3 I created a separate branch to fix this issue and github pages don't allow to create a live link for branches other than master branch
It will be great if you can test the PR locally.

**Comment by Jigar3** [comment]
@CleverFool77 You could use netilfy, it allows to deploy the static site from any branch.

**Comment by CleverFool77** [comment]
@Jigar3 @Anupam-dagar 
Here is the live link for the PR :)
https://ecstatic-leavitt-0eedfc.netlify.com/

**Pull request merged**
