### PR TITLE
Add landing page and Navbar

### LINKED ISSUE #22: improve the navbar
the current navbar looks too plain and a bad color scheme. Also the logo in navbar section doesn't looks good. Improve the navbar.

### PR DESCRIPTION
**Pull request by CleverFool77**
# Description

Improve the landing page and Navbar

Fixes #22 #25 

## Live link
https://ecstatic-leavitt-0eedfc.netlify.com/

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by ananya-agrawal** [comment]
@CleverFool77 the footer is no longer coming and the color of contributors section is also changed, these changes were not supposed to come under this issue.

**Comment by CleverFool77** [comment]
@ananya-agrawal I'm push the complete changes soon.

**Comment by ananya-agrawal** [comment]
@CleverFool77 please do it at the earliest possible, we are not able to open more issues without this getting merged

**Comment by ananya-agrawal** [comment]
@CleverFool77 that earlier navbar you made was looking awesome :stuck_out_tongue: put it back nah :stuck_out_tongue: . 
and the pr is changing color of contributors section which is not supposed to be done in this.
and navbar is showing duplicate entries
screenshot from 2019-01-29 00-20-44

**Comment by CleverFool77** [comment]
@ananya-agrawal i removed it by mistake while resolving merge conflict. By evening I'll resolve it

**Pull request merged**
