### PR TITLE
Fixes bugs due to gallery bootstrap

### LINKED ISSUE #62: size of about card is changed, get it back to previous one.
screenshot from 2019-02-04 10-44-38

### PR DESCRIPTION
**Pull request by Archies11**
# Description

I have added the image carousel for the bootstrap already present in the code. 

Fixes #62 #63 #64 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

## Live Gh-Pages Link
[Live Link] https://dazzling-dubinsky-d06ec4.netlify.com/

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by pradeepgangwar** [comment]
Changes look good to me. You should try to fix each issue in separate PR. But this looks fine as there are less changes. Be careful while updating leaderboard. Make sure mentors approve all the points. There are high chances of discarding some requests thinking it as duplicate.

**Comment by pradeepgangwar** [comment]
Assigning @ananya-agrawal as I am not familiar with this repo's code. Review the changes as a final check and merge the PR if it is ok.

**Comment by Archies11** [comment]
> Changes look good to me. You should try to fix each issue in separate PR. But this looks fine as there are less changes. Be careful while updating leaderboard. Make sure mentors approve all the points. There are high chances of discarding some requests thinking it as duplicate.

@pradeepgangwar I have mentioned the lnik of this PR in the other PRs I made for the corresponding bugs ], will that be enough?

**Comment by Anupam-dagar** [comment]
I need to discuss internally for the point allocation for this. You may fill the leaderboard normally, anything regarding points will be done later.

**Pull request merged**
