### PR TITLE
Fixes#63

### LINKED ISSUE #63: font size of one-line description and social links in contributors card is changed.Fix it
fix the css.

### PR DESCRIPTION
**Pull request by Archies11**
# Description

Changed the font size of contributors cards back to normal.

Fixes #63

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

## Live Gh-Pages Link
[Live Link]https://wizardly-goldwasser-b4f5f6.netlify.com/

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Archies11** [comment]
Since the changes are made in a popup, i cant take a snip .

**Comment by Anupam-dagar** [comment]
@Archies11 I have updated the issue description. As there is a font sizing issue for the complete website, it might have happened due to one of the previous commit. As a fix make the font size consistent for the complete website.

**Comment by Anupam-dagar** [comment]
So i missed one line of code during review that was you adding a bootstrap 3 css. The website currently uses a Bootstrap v4 css. You can't mix 2 versions of same framework in the same website and also Bootstrap 4 brought itself many changes from v3. I suggest you to fix the gallery first and work on these later if required.

Till then I will close these PR's.

**Comment by Archies11** [comment]
Pr that solves this issue: https://github.com/opencodeiiita/CodeFemme/pull/76

**Pull request closed without merging**
