### PR TITLE
Fixes Bugs due to gallery bootstrap

### LINKED ISSUE #62: size of about card is changed, get it back to previous one.
screenshot from 2019-02-04 10-44-38

### LINKED ISSUE #63: font size of one-line description and social links in contributors card is changed.Fix it
fix the css.

### LINKED ISSUE #64: fix footer social icons and font

### PR DESCRIPTION
**Pull request by Archies11**
# Description

Made certain changes so as to resolve the bugs in the site.

Fixes #63 
Fixes #62 
Fixes #64

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

## Live Gh-Pages Link
[Live Link]https://musing-kare-c5e125.netlify.com/

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
@Archies11 I'll review it in sometime since it includes some js code debugging.

**Comment by Archies11** [comment]
@Anupam-dagar the code runs fine when placed in a separate html file but when embedded in the index.html, it shows the above issues...

**Comment by Anupam-dagar** [comment]
I have a tight schedule till tomorrow, can't check before day after
tomorrow. Maybe see how bootstrap 4 implements a carousel.
For review on this PR, I am pitching in @pradeepgangwar.

**Comment by Archies11** [comment]
New PR: https://github.com/opencodeiiita/CodeFemme/pull/76

**Pull request closed without merging**
