### PR TITLE
Add lekhika-dugtal to contributors

### LINKED ISSUE #37: add yourself to the contributor section.
add a card for yourself in the contributor section. Make sure to write a one line bio.
after adding yourself, make sure to do a social media post saying you are contributing to codefemme or added yourself to codefemme part of opencode19 or any other relevant post. (facebook, twitter,linkedin or any other platform, no stories). Comment the link of the post in the pull request. This is a mandatory condition to get your PR merged.

### PR DESCRIPTION
**Pull request by CleverFool77**
# Description
I added myself to contributors and I created a assets/img folder to maintain images.

Fixes #37 

## Live Link
https://cleverfool77.github.io/CodeFemme/

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

## Social Media Link
https://twitter.com/DugtalLekhika/status/1090665513963773953

### CODE REVIEW

**Comment by CleverFool77** [comment]
@aswinzz I added live link in PR

**Comment by Anupam-dagar** [comment]
@CleverFool77 Changes looks good to me.
I have updated the issue. Please comment the social media post link so that we can merge the PR.

**Comment by CleverFool77** [comment]
@Anupam-dagar I added social-media link in comment.

**Comment by Anupam-dagar** [comment]
@CleverFool77 LGTM :tada: 
Thanks for your contribution. Merged.

**Pull request merged**
